FROM node:latest

# add the sources to the image
ADD . /usr/src/azure-iot-sdks

# setup environment variables for e2e tests
ENV IOTHUB_CONNECTION_STRING HostName=raj-devhub-01.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=cOe7mjaxbrHf61lBKxUOPa5QsuksXZAb0QTfE8dTXnk=
ENV IOTHUB_NAME raj-devhub-01
ENV IOTHUB_EVENTHUB_LISTEN_NAME raj-devhub-01
ENV IOTHUB_SUFFIX azure-devices.net
ENV IOTHUB_POLICY_NAME iothubowner
ENV IOTHUB_POLICY_KEY cOe7mjaxbrHf61lBKxUOPa5QsuksXZAb0QTfE8dTXnk
ENV IOTHUB_EVENTHUB_ACCESS_KEY cOe7mjaxbrHf61lBKxUOPa5QsuksXZAb0QTfE8dTXnk
ENV IOTHUB_EVENTHUB_CONNECTION_STRING iothub-ehub-raj-devhub-1443-88deea5de9;SharedAccessKeyName=iothubowner;SharedAccessKey=cOe7mjaxbrHf61lBKxUOPa5QsuksXZAb0QTfE8dTXnk
ENV IOTHUB_EVENTHUB_CONSUMER_GROUP $Default
ENV IOTHUB_PARTITION_COUNT 2
ENV IOTHUB_DEVICE_ID device-01
ENV IOTHUB_DEVICE_KEY 5u0B2ZAyEsOnW1hP9Lfu2QPMg4W1LgnubJRnwyhnNzM=
ENV IOTHUB_SHARED_ACCESS_SIGNATURE SharedAccessSignature sr=raj-devhub-01.azure-devices.net&sig=sm0qnNuVP6oX5SJBlpys3786GHLge3pxlaYbs2Pjzw8%3d&se=1475712451&skn=iothubowner

# build node sdk
RUN /usr/src/azure-iot-sdks/build/linux_node.sh

# set working dir to root of repo
WORKDIR /usr/src/azure-iot-sdks
